package br.ueg.mobile.exitus.modelo;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.2.0
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.ArrayList;
import java.util.Hashtable;

import br.ueg.mobile.exitus.servico_cliente.ExtendedSoapSerializationEnvelope;

public class AgendarSincronizacaoFrequencia extends AttributeContainer implements KvmSerializable
{

    public String token;
    
    public ArrayList<Frequencia> frequencias =new ArrayList<>();
    private transient Object __source;    
    
    public void loadFromSoap(Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }

    }

    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("arg0"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.token = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.token = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("arg1"))
        {
            if(obj!=null)
            {
                if(this.frequencias ==null)
                {
                    this.frequencias = new ArrayList<>();
                }
                Object j =obj;
                Frequencia j1= (Frequencia)__envelope.get(j,Frequencia.class,false);
                this.frequencias.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.token !=null?this.token :SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.frequencias.size())
        {
            Object arg1 = this.frequencias.get(propertyIndex-(1));
            return arg1!=null?arg1:SoapPrimitive.NullNilElement;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 1+ frequencias.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "arg0";
            info.namespace= "";
        }
        if(propertyIndex>=1 && propertyIndex < 1+this.frequencias.size())
        {
            info.type = Frequencia.class;
            info.name = "arg1";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}

