package br.ueg.mobile.exitus.servico_cliente;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface ServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
